### ISSUE TITLE
Add two variants of Sliding Window Algorithm (commented) in Python Folder

### ISSUE THREAD

**Issue by yuvrajverma01** [DSC-ChitkaraUniv/Hacktoberfest_2021#1]
Hi **_Maintainer_**,

This issue is to request you that I would like to add two **_variants of Sliding Window Algorithm_**, fully explained and commented, **_in Python Folder_** to provide value to the seekers of this repository.

**_Variant 1:_** Maximum/Minimum Sum of K size subarray with time Complexity of **O(n)**.
**_Variant 2:_** Smallest subarray with given Sum with time Complexity of **O(n²)**.

**Comment by bhaveshgoyal182** [comment]
Hey @yuvrajverma01 ,
Go ahead, just make sure you follow  the rules mentioned in Readme👍🏻
