### ISSUE TITLE
Add a Example of CNN model using CIFAR dataset & keras library  in Deep Learning Folder 

### ISSUE THREAD

**Issue by ManthanShettigar** [DSC-ChitkaraUniv/Hacktoberfest_2021#16]
Hello Maintainer,

This issue is to request you that I would like to add a Deep Learning python notebook built by CNN  using the CIFAR-10 dataset which consists of 10 different image types.

Notebook structure ( to do list) :
- [x] Fetch CIFAR dataset
- [x] Data preprocessing
- [x] Build and train CNN model
- [x] Evaluate model ( loss,accuracy) 
- [x] Plot heatmap of Confusion matrix
- [x] Predict the label of image

Please assign me to work on this issue.

**Comment by bhaveshgoyal182** [comment]
Hey @ManthanShettigar ,
You are good to go 👍🏻

**Comment by ManthanShettigar** [comment]
Created a PR , please do check @bhaveshgoyal182 , if any changes are needed , do let me know .
Thank you & happy hacking :)
