### ISSUE TITLE
Add the Trapping Rainwater Problem Approach in the java folder.

### ISSUE THREAD

**Issue by Psaluja706** [DSC-ChitkaraUniv/Hacktoberfest_2021#6]
Hi Maintainer,
This issue is to request you that I would like to add  the Trapping Rainwater Problem Approach in the java folder of this repository, please assign me this issue.

**Comment by bhaveshgoyal182** [comment]
Hey @Psaluja706  ,
Go ahead, just make sure you follow the rules mentioned in Readme👍🏻
